# Auto-generated by scripts/generate_ui_tests_from_prompt.py

TIMEOUT_MS = 5000


def _open_login(page, base_url):
    page.goto(base_url.rstrip('/') + '/')


def _login(page, username, password):
    page.locator('#user-name').fill(username, timeout=TIMEOUT_MS)
    page.locator('#password').fill(password, timeout=TIMEOUT_MS)
    page.locator('#login-button').click(timeout=TIMEOUT_MS)


def _assert_login_error(page, text='Epic sadface'):
    page.wait_for_selector("[data-test='error']", timeout=TIMEOUT_MS)
    assert text in page.locator("[data-test='error']").inner_text(timeout=TIMEOUT_MS)

def test_valid_login_standard_user(page, base_url):
    """Valid Login with standard_user/secret_sauce"""
    _open_login(page, base_url)
    _login(page, 'standard_user', 'secret_sauce')
    assert '/inventory.html' in page.url
    assert 'Products' in page.locator("[data-test='title']").inner_text(timeout=TIMEOUT_MS)

def test_invalid_login_standard_user_secret_sauce1(page, base_url):
    """Invalid Login with standard_user/secret_sauce1"""
    _open_login(page, base_url)
    _login(page, 'standard_user', 'secret_sauce1')
    _assert_login_error(page)

def test_invalid_login_error_user_secret_sauce(page, base_url):
    """Invalid Login with error_user/secret_sauce"""
    _open_login(page, base_url)
    _login(page, 'error_user', 'secret_sauce')
    _assert_login_error(page)

def test_login_add_to_cart_checkout_sauce_labs_fleece_jacket(page, base_url):
    """Login with standard_user. Then add "Sauce Labs Fleece Jacket" to cart . Then complete checkout using random details"""
    _open_login(page, base_url)
    _login(page, 'standard_user', 'secret_sauce')
    page.locator("[data-test='add-to-cart-sauce-labs-fleece-jacket']").click(timeout=TIMEOUT_MS)
    page.locator('.shopping_cart_link').click(timeout=TIMEOUT_MS)
    assert 'Sauce Labs Fleece Jacket' in page.locator('.inventory_item_name').inner_text(timeout=TIMEOUT_MS)
    page.locator("[data-test='checkout']").click(timeout=TIMEOUT_MS)
    page.locator("[data-test='firstName']").fill('Auto', timeout=TIMEOUT_MS)
    page.locator("[data-test='lastName']").fill('User', timeout=TIMEOUT_MS)
    page.locator("[data-test='postalCode']").fill('12345', timeout=TIMEOUT_MS)
    page.locator("[data-test='continue']").click(timeout=TIMEOUT_MS)
    page.locator("[data-test='finish']").click(timeout=TIMEOUT_MS)
    assert 'Thank you for your order!' in page.locator("[data-test='complete-header']").inner_text(timeout=TIMEOUT_MS)
