# Auto-generated by scripts/generate_ui_tests_from_prompt.py

def test_valid_login_standard_user(page, base_url):
    """Valid Login with standard_user/secret_sauce"""
    page.goto(base_url.rstrip('/') + '/')
    page.locator('#user-name').fill('standard_user', timeout=5000)
    page.locator('#password').fill('secret_sauce', timeout=5000)
    page.locator('#login-button').click(timeout=5000)
    assert '/inventory.html' in page.url
    assert 'Products' in page.locator("[data-test='title']").inner_text(timeout=5000)

def test_invalid_login_standard_user_secret_sauce1(page, base_url):
    """Invalid Login with standard_user/secret_sauce1"""
    page.goto(base_url.rstrip('/') + '/')
    page.locator('#user-name').fill('standard_user', timeout=5000)
    page.locator('#password').fill('secret_sauce1', timeout=5000)
    page.locator('#login-button').click(timeout=5000)
    page.wait_for_selector("[data-test='error']", timeout=5000)
    assert 'Epic sadface' in page.locator("[data-test='error']").inner_text(timeout=5000)

def test_invalid_login_error_user_secret_sauce(page, base_url):
    """Invalid Login with error_user/secret_sauce"""
    page.goto(base_url.rstrip('/') + '/')
    page.locator('#user-name').fill('error_user', timeout=5000)
    page.locator('#password').fill('secret_sauce', timeout=5000)
    page.locator('#login-button').click(timeout=5000)
    page.wait_for_selector("[data-test='error']", timeout=5000)
    assert 'Epic sadface' in page.locator("[data-test='error']").inner_text(timeout=5000)

def test_login_add_to_cart_checkout_sauce_labs_fleece_jacket(page, base_url):
    """Login with standard_user. Then add "Sauce Labs Fleece Jacket" to cart . Then complete checkout using random details"""
    page.goto(base_url.rstrip('/') + '/')
    page.locator('#user-name').fill('standard_user', timeout=5000)
    page.locator('#password').fill('secret_sauce', timeout=5000)
    page.locator('#login-button').click(timeout=5000)
    page.locator("[data-test='add-to-cart-sauce-labs-fleece-jacket']").click(timeout=5000)
    page.locator('.shopping_cart_link').click(timeout=5000)
    assert 'Sauce Labs Fleece Jacket' in page.locator('.inventory_item_name').inner_text(timeout=5000)
    page.locator("[data-test='checkout']").click(timeout=5000)
    page.locator("[data-test='firstName']").fill('Auto', timeout=5000)
    page.locator("[data-test='lastName']").fill('User', timeout=5000)
    page.locator("[data-test='postalCode']").fill('12345', timeout=5000)
    page.locator("[data-test='continue']").click(timeout=5000)
    page.locator("[data-test='finish']").click(timeout=5000)
    assert 'Thank you for your order!' in page.locator("[data-test='complete-header']").inner_text(timeout=5000)
